### ISSUE TITLE
Success factor should be optional, not mandatory, part of dependency on ReplicaSet

### ISSUE THREAD

**Issue by gluke77** [Mirantis/k8s-AppController#38]

**Comment by jellonek** [comment]
In current implementation it is optional and part of dependency on ReplicaSet, but this metadata is propagated on replicaset resource, because of current logic in scheduler which requires refactor (dependency tree reuses already created scheduled resources for each dependency, so there is no way to distinguish different dependencies on same resource with different metadata).

Connected with #37

**Comment by gluke77** [comment]
Since 'different dependencies on the same resource' is in scope of #37,  I think this one could be closed.
