### ISSUE TITLE
Should property be part of Resource Definition, Dependency or both?

### ISSUE THREAD

**Issue by gluke77** [Mirantis/k8s-AppController#39]
Issue: properties (such as success factor for ReplicaSet) from one side belong to Resource Definition. Proof: even if nobody depends on RC, we still wait for its status to be 'ready' and we need SF for that. From the other side, for already existing resources this could not be part of resource definition because there is no resource definition for existing resources. So we want them (properties) to be the part of dependency. We could probably allow properties both in resdefs and dependencies, but we need a dedicated check that these do not contradict. Or we could have resource definitions for already existing resources (eeew).

**Comment by pigmej** [comment]
I think we should go with keeping that *only* in deps. Having that in 2 places will be very problematic.

It's not even about existing resoruces, it's about *any* resource that is leaf (because it's not a parent in any dep).

For temporary workaround we can add some noop dep to leafs kinda like:
```
parent: leaf_resource
child: something_noop
```

And `something_noop` will just allow us to wait for `leaf_resource` to be ok, which means that SF will be checked.

**Comment by gluke77** [comment]
that sounds like a plan, tnx
